openapi: 3.0.0
info:
  title: Secret Server API
  version: 1.0.0
paths:
  /api/v1/secrets:
    post:
      summary: Titok létrehozása
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                secret:
                  type: string
                maxReads:
                  type: integer
                ttlSeconds:
                  type: integer
      responses:
        '201':
          description: Titok sikeresen létrehozva
